HEADER_DIV_ID = 'HEAD1'

DROPDOWN_TITLE = 'DRPT1'
DROPDOWN_ID = 'DRP1'

DATEPICKER_TITLE = 'DPKT1'
DATEPICKER_ID = 'DPK1'

FIGURE_TITLE = 'FIGT1'
FIGURE_ID = 'FIG1'

BUTTON_ID = 'BTN1'

BACKGROUND_DIV = 'BG1'